language: php

php:
    - 5.6
    - 7.0


before_install:
    - composer selfupdate
    - composer global require hirak/prestissimo
    - composer dump-autoload

script:
    - ./vendor/bin/grumphp run
